version: 2

models:  
  - name: dim_customers
    description: "Customer dimension table with lifetime metrics and product preferences per unique custmer id"
    columns:
      - name: customer_unique_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: "Date of customer's first order"
        tests:
          - not_null
      - name: last_order_date
        description: "Date of customer's last order"
        tests:
          - not_null
      - name: most_popular_category
        description: "Most frequently purchased product category"

  - name: dim_customers_geography
    description: "Customer geography dimension with location data"
    columns:
      - name: customer_unique_id
        description: "Unique customer identifier for analysis"
        tests:
          - not_null
      - name: city
        description: "Customer city (lowercase)"
        tests:
          - not_null
      - name: state
        description: "Customer state (uppercase)"
        tests:
          - not_null
      - name: geolocation_lat
        description: "Customer latitude"
        tests:
          - not_null
      - name: geolocation_lng
        description: "Customer longitude"
        tests:
          - not_null

  - name: dim_products
    description: "Product dimension with category translations"
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - unique
          - not_null
      - name: product_category_name
        description: "Product category name (lowercase)"
        tests:
          - not_null
      - name: product_category_name_english
        description: "Product category name in English"

  - name: dim_sellers_geography
    description: "Seller geography dimension with location data"
    columns:
      - name: seller_id
        description: "Unique seller identifier"
        tests:
          - unique
          - not_null
      - name: city
        description: "Seller city (lowercase)"
        tests:
          - not_null
      - name: state
        description: "Seller state (uppercase)"
        tests:
          - not_null
      - name: geolocation_lat
        description: "Seller latitude"
        tests:
          - not_null
      - name: geolocation_lng
        description: "Seller longitude"
        tests:
          - not_null

  # === FACT TABLES ===

  - name: fct_customers_products
    description: "Customer product engagement fact table with lifetime metrics"
    columns:
      - name: customer_unique_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
      - name: total_orders_count
        description: "Total number of orders placed by customer"
        tests:
          - not_null
      - name: lifetime_total_value
        description: "Total lifetime value from all orders"
        tests:
          - not_null
      - name: lifetime_freight_value
        description: "Total lifetime freight value"
        tests:
          - not_null
      - name: lifetime_payment_value
        description: "Total lifetime payment value"
        tests:
          - not_null
      - name: distinct_products_purchased
        description: "Number of distinct products purchased"
        tests:
          - not_null
      - name: distinct_sellers_used
        description: "Number of distinct sellers used"
        tests:
          - not_null
      - name: avg_installments
        description: "Average number of payment installments"
        tests:
          - not_null
      - name: max_installments_used
        description: "Maximum number of installments used"
        tests:
          - not_null

  - name: fct_fulfillment_metrics
    description: "Seller fulfillment performance metrics"
    columns:
      - name: seller_id
        description: "Unique seller identifier"
        tests:
          - unique
          - not_null
      - name: total_orders
        description: "Total number of orders handled"
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue generated"
        tests:
          - not_null
      - name: total_freight
        description: "Total freight value"
        tests:
          - not_null
      - name: avg_price_per_order
        description: "Average price per order"
        tests:
          - not_null
      - name: avg_freight_per_order
        description: "Average freight per order"
        tests:
          - not_null
      - name: avg_delivery_days
        description: "Average delivery time in days"
        tests:
          - not_null
      - name: min_delivery_days
        description: "Minimum delivery time in days"
        tests:
          - not_null
      - name: max_delivery_days
        description: "Maximum delivery time in days"
        tests:
          - not_null
      - name: delivery_days_stddev
        description: "Standard deviation of delivery days"
        tests:
          - not_null

  - name: fct_orders_stats
    description: "Order-level aggregated statistics"
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Customer identifier"
        tests:
          - not_null
      - name: num_items
        description: "Number of items in the order"
        tests:
          - not_null
      - name: num_products
        description: "Number of distinct products in the order"
        tests:
          - not_null
      - name: total_price
        description: "Total price of the order"
        tests:
          - not_null
      - name: total_freight
        description: "Total freight value of the order"
        tests:
          - not_null
      - name: avg_price
        description: "Average price per item"
        tests:
          - not_null
      - name: avg_freight
        description: "Average freight per item"
        tests:
          - not_null
      - name: high_value_order_flag
        description: "Flag indicating if order value > 100"
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      - name: price_per_item
        description: "Price per item ratio"
        tests:
          - not_null
      - name: freight_ratio
        description: "Freight to price ratio"
        tests:
          - not_null

  - name: fct_product_performance
    description: "Product performance metrics by month"
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - not_null
      - name: performance_month
        description: "Month for performance metrics"
        tests:
          - not_null
      - name: total_orders
        description: "Total number of orders for this product"
        tests:
          - not_null
      - name: total_items_sold
        description: "Total number of items sold"
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue generated"
        tests:
          - not_null
      - name: avg_sale_price
        description: "Average sale price"
        tests:
          - not_null
      - name: min_sale_price
        description: "Minimum sale price"
        tests:
          - not_null
      - name: max_sale_price
        description: "Maximum sale price"
        tests:
          - not_null
      - name: total_freight_cost
        description: "Total freight cost"
        tests:
          - not_null
      - name: avg_freight_per_item
        description: "Average freight per item"
        tests:
          - not_null
      - name: unique_customers
        description: "Number of unique customers who purchased this product"
        tests:
          - not_null
      - name: avg_product_weight_g
        description: "Average product weight in grams"
        tests:
          - not_null
      - name: avg_product_length_cm
        description: "Average product length in cm"
        tests:
          - not_null
      - name: avg_product_height_cm
        description: "Average product height in cm"
        tests:
          - not_null
      - name: avg_product_width_cm
        description: "Average product width in cm"
        tests:
          - not_null
      - name: avg_photos_per_product
        description: "Average number of photos per product"
        tests:
          - not_null
      - name: revenue_per_item
        description: "Revenue per item ratio"
        tests:
          - not_null
      - name: revenue_per_gram
        description: "Revenue per gram ratio"
        tests:
          - not_null

# RELATIONSHIP TESTS ===
tests:
  - relationships:
      source: ref('dim_customers')
      from: customer_unique_id
      to: ref('stg_customers')
      to_field: customer_unique_id
      config:
        severity: warn

  - relationships:
      source: ref('fct_customers_products')
      from: customer_unique_id
      to: ref('dim_customers')
      to_field: customer_unique_id
      config:
        severity: warn

  - relationships:
      source: ref('fct_fulfillment_metrics')
      from: seller_id
      to: ref('dim_sellers_geography')
      to_field: seller_id
      config:
        severity: warn

  - relationships:
      source: ref('fct_product_performance')
      from: product_id
      to: ref('dim_products')
      to_field: product_id
      config:
        severity: warn

  - relationships:
      source: ref('fct_orders_stats')
      from: customer_unique_id
      to: ref('dim_customers')
      to_field: customer_unique_id
      config:
        severity: warn